quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USERNAME}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_URL}

quarkus.hibernate-orm.schema-generation.database.action=update
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.log.format-sql=false

quarkus.oidc.application-type=service
quarkus.oidc.auth-server-url=${AUTH_URL}
quarkus.oidc.client-id=authenticated
mp.jwt.verify.issuer=${AUTH_URL}
mp.jwt.verify.audiences=authenticated

quarkus.http.auth.permission.options.paths=/*
quarkus.http.auth.permission.options.methods=OPTIONS
quarkus.http.auth.permission.options.policy=permit

quarkus.http.auth.permission.secured.paths=/*
quarkus.http.auth.permission.secured.policy=authenticated

quarkus.http.cors.origins=http://localhost:4200
quarkus.http.cors.methods=GET,PUT,POST,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with
quarkus.http.cors.exposed-headers=authorization, content-type

app.whitelist.emails=${APP_WHITELIST_EMAILS}